name: Publish to PyPi


# TODO: actually plan when we want to trigger this job
# maybe move it into the package job so all release-based actions are together
#  - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to pull the pypi token from'
        type: environment
        required: true
  push:
    tags: release
    branches: jac/pypi

  buildwheels:
    name: Build dist files for PyPi
    needs: createrelease
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Build dist files
        run: |
          python -m pip install --upgrade pip
          pip install -e
          python setup.py sdist --formats=gztar,zip

# This action assumes files exist in /dist unless told otherwise
# https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/
  publish:
    - name: Publish distribution 📦 to Test PyPI
      if: startsWith(environment, 'test')
      needs: buildwheels
      uses: pypa/gh-action-pypi-publish@release/v1  # license BSD-2
      with:
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/
    - name: Publish distribution 📦 to PyPI
      if: startsWith(github.ref, 'refs/tags')
      needs: buildwheels
      uses: pypa/gh-action-pypi-publish@release/v1  # license BSD-2
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}